# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JenkinsQueueJob@2
  name: Build
  inputs:
    serverEndpoint: 'Jenkins'
    jobName: 'nodejs'
    captureConsole: true
    capturePipeline: true
    isParameterizedJob: false

- task: JenkinsDownloadArtifacts@1
  inputs:
    jenkinsServerConnection: 'Jenkins'
    jobName: 'nodejs'
    saveTo: 'jenkinsArtifacts'
    jenkinsBuild: 'BuildNumber'
    jenkinsBuildNumber: '$(Build.JENKINS_JOB_ID)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'SP'
    appType: 'webAppLinux'
    WebAppName: 'webappkzb4b7r4ap64y-webapp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'